apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: laravel-data-claim
  namespace: server-hub
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi