apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: games
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000
      containers:
        - name: minecraft
          image: itzg/minecraft-server:latest
          tty: true
          stdin: true
          ports:
            - containerPort: 25565
          envFrom:
            - configMapRef:
                name: minecraft-env
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-data-claim
        - name: tmp
          emptyDir: {}