apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: server-hub
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      automountServiceAccountToken: false
      containers:
      - name: redis
        image: redis:7
        command: 
          - redis-server
        args:
          - --save
          - ""
          - --appendonly
          - "no"
          - --aclfile
          - /etc/redis/users.acl
        volumeMounts:
          - name: redis-acl
            mountPath: /etc/redis/users.acl
            subPath: users.acl
            readOnly: true
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
          runAsGroup: 999
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
      
      volumes:
        - name: redis-acl
          secret:
            secretName: redis-acl