apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: server-hub
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7
        command: 
          - redis-server
        args:
          - --save
          - ""
          - --appendonly
          - "no"
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
          runAsGroup: 999
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault